controller_list:
  - name: fake_panda_arm_controller
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
  - name: fake_hand_controller
    joints:
      - panda1_finger_joint1
      - panda1_finger_joint2
initial:
  - group: panda_arm_hand
    pose: ready
