position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
  constraints:
    goal_time: 0.5
    panda2_joint1:
      goal: 0.05
    panda2_joint2:
      goal: 0.05
    panda2_joint3:
      goal: 0.05
    panda2_joint4:
      goal: 0.05
    panda2_joint5:
      goal: 0.05
    panda2_joint6:
      goal: 0.05
    panda2_joint7:
      goal: 0.05

velocity_jointgroup_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
  panda2_joint1:
    p: 100.0
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint2:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint3:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint4:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint5:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint6:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint7:
    pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  constraints:
    goal_time: 0.5
    panda2_joint1:
      goal: 0.05
    panda2_joint2:
      goal: 0.05
    panda2_joint3:
      goal: 0.05
    panda2_joint4:
      goal: 0.05
    panda2_joint5:
      goal: 0.05
    panda2_joint6:
      goal: 0.05
    panda2_joint7:
      goal: 0.05

effort_jointgroup_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
  constraints:
    goal_time: 0.5
    panda2_joint1:
      goal: 0.0005
    panda2_joint2:
      goal: 0.0005
    panda2_joint3:
      goal: 0.0005
    panda2_joint4:
      goal: 0.0005
    panda2_joint5:
      goal: 0.0005
    panda2_joint6:
      goal: 0.0005
    panda2_joint7:
      goal: 0.0005

effort_position_jointgroup_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
  panda2_joint1:
    pid: {p: 1.8, i: 0.5, d: 0.0, i_clamp_min: -0.5, i_clamp_max: 0.5, antiwindup: true}
  panda2_joint2:
    pid: {p: 1.4, i: 1.5, d: 0.8, i_clamp_min: -0.4, i_clamp_max: 0.4, antiwindup: true}
  panda2_joint3:
    pid: {p: 3.5, i: 2.0, d: 0.5, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}
  panda2_joint4:
    pid: {p: 3.0, i: 2.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}
  panda2_joint5:
    pid: {p: 5.0, i: 2.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}
  panda2_joint6:
    pid: {p: 13.0, i: 6.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}
  panda2_joint7:
    pid: {p: 0.8, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1, antiwindup: true}


gazebo_ros_control/pid_gains:
  panda2_joint1: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint2: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint3: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint4: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint5: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint6: {p: 100.0, i: 0.0, d: 0.01}
  panda2_joint7: {p: 100.0, i: 0.0, d: 0.01}


franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  joint_names:
    - panda2_joint1
    - panda2_joint2
    - panda2_joint3
    - panda2_joint4
    - panda2_joint5
    - panda2_joint6
    - panda2_joint7
  arm_id: panda2


# The joint state controller handles publishing transforms for any moving joints
franka_sim_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

franka_left_finger_controller:
  type: effort_controllers/JointPositionController
  joint: panda2_finger_joint1
  pid: {p: 1000.0, i: 5.0, d: 100.0, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}

franka_right_finger_controller:
  type: effort_controllers/JointPositionController
  joint: panda2_finger_joint2
  pid: {p: 1000.0, i: 5.0, d: 100.0, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}
