controller_list:
  - name: fake_panda_arm_controller
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
  - name: fake_hand_controller
    joints:
      - panda2_finger_joint1
      - panda2_finger_joint2
initial:
  - group: panda_arm_hand
    pose: ready
