 controller_list:
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
  - name: franka_gripper
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - panda2_finger_joint1
      - panda2_finger_joint2
